- hosts: all
  gather_facts: yes
  become: yes
  vars_files:
    - vars.yaml
  vars:
    ansible_ssh_private_key_file: '{{main_key }}'

  roles:
    - role: system
      tags: system

    - role: docker
      tags: docker

    - role: ssh
      tags: ssh

    - role: software
      tags: software
